/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja.Views.Vendas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import loja.Controller.ProdutoController;
import loja.Controller.VendaController;
import loja.Models.Produto;
import loja.Models.Venda;

/**
 *
 * @author Rogerio
 */
public class VendasView extends javax.swing.JFrame {

    VendaController vendaController = new VendaController();
    private int numeroVenda;
    DefaultListModel model = new DefaultListModel();
    List<Produto> listaProdutoAdicionado = new ArrayList<>();
    double valorVenda;
    /**
     * Creates new form VendasView
     */
    public VendasView() {
        initComponents();
        numeroVenda = vendaController.retornarNumeroVenda();
        if(numeroVenda == 0){
            numeroVenda = 1;
        }
                
        lblNumeroVenda.setText(String.valueOf(numeroVenda));
        
        
        listProdutos.setModel(model);
        String Cabecalho = "Código" + "     " + "Descrição" + "               " + "Preço";
        model.addElement(String.format(Cabecalho)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoBusca = new javax.swing.JTextField();
        AdicionarProdutoBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        confirmarVendaBtn = new javax.swing.JButton();
        cancelarVendaBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNumeroVenda = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProdutos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCodigoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, 219, -1));

        AdicionarProdutoBtn.setText("Adicionar");
        AdicionarProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarProdutoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarProdutoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 98, -1, -1));

        jLabel2.setText("Localizar Produtos (somente números) ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 75, 240, -1));

        confirmarVendaBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmarVendaBtn.setText("Confirmar Venda");
        confirmarVendaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarVendaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarVendaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 170, 41));

        cancelarVendaBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelarVendaBtn.setText("Cancelar");
        cancelarVendaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVendaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarVendaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 120, 41));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Venda Atual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor Total:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        lblNumeroVenda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(lblNumeroVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 13, 67, 20));

        lblValorTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblValorTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 140, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("R$");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        listProdutos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 330, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarProdutoBtnActionPerformed
        
        if(txtCodigoBusca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo de busca");
        }else{
                ProdutoController produtoController = new ProdutoController();
                Produto produto = new Produto();
                produto.setCodigoProduto(Integer.parseInt(txtCodigoBusca.getText()));
                boolean jaExiste = false;

                produto = produtoController.buscarProdutoAdicionar(produto);
                if(produto.getDescricaoProduto() != null){
                    for(Produto prod: listaProdutoAdicionado ){
                        if(produto.getCodigoProduto() == prod.getCodigoProduto()){
                            jaExiste = true;
                            JOptionPane.showMessageDialog(null, "Produto já adicionado");
                            txtCodigoBusca.setText("");
                        }
                    }
                    if(!jaExiste){
                        listaProdutoAdicionado.add(produto);
                        valorVenda = valorVenda + produto.getPrecoProduto();
                        lblValorTotal.setText(String.valueOf(valorVenda));
                        String produtoLista = produto.getCodigoProduto() + "                " + produto.getDescricaoProduto() + "                         " + produto.getPrecoProduto();
                        model.addElement(String.format(produtoLista)); 
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Produto Não Cadastrado");
                    txtCodigoBusca.setText("");
                }
            }
        
         
    }//GEN-LAST:event_AdicionarProdutoBtnActionPerformed

    private void cancelarVendaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVendaBtnActionPerformed
        Object[] options = { "Confirmar", "Cancelar" };
        int resposta = JOptionPane.showOptionDialog(null, "Deseja cancelar a Venda Atual?", "Atenção", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(resposta == 0){
            Venda venda = new Venda();
            venda.setNumeroVenda(Integer.parseInt(lblNumeroVenda.getText()));
            vendaController.cancelarVenda(venda);
            this.dispose();
        }
    }//GEN-LAST:event_cancelarVendaBtnActionPerformed

    private void confirmarVendaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarVendaBtnActionPerformed
        Object[] options = { "Confirmar", "Cancelar" };
        int resposta = JOptionPane.showOptionDialog(null, "Confirmar a Venda Atual?", "Atenção", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(resposta == 0){
            Venda venda = new Venda();
            venda.setNumeroVenda(Integer.parseInt(lblNumeroVenda.getText()));
            venda.setTotalVenda(Double.parseDouble(lblNumeroVenda.getText()));
            venda.setListaProdutosVenda(listaProdutoAdicionado);
            vendaController.confirmarVenda(venda);
            JOptionPane.showMessageDialog(null, "Venda Cadastrada com Sucesso");
            this.dispose();
            new VendasView().setVisible(true);
        }
    }//GEN-LAST:event_confirmarVendaBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarProdutoBtn;
    private javax.swing.JButton cancelarVendaBtn;
    private javax.swing.JButton confirmarVendaBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroVenda;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JList<String> listProdutos;
    private javax.swing.JTextField txtCodigoBusca;
    // End of variables declaration//GEN-END:variables
}
