/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja.Views.Principal;

import loja.Principal;
import loja.Util.Sessao;
import loja.Views.Funcionarios.FinancasView;
import loja.Views.Produtos.ProdutosCadastrar;
import loja.Views.Vendas.VendasView;

/**
 *
 * @author rogerio.leite
 */
public class TelaInicialView extends javax.swing.JFrame {
    
    public int permissaoAcesso;
    
    /**
     * Creates new form Tela_Inicial
     */
    public TelaInicialView(int permissao) {     
        this.permissaoAcesso = permissao;
        initComponents();
        this.setLocationRelativeTo(null);
        
        if(permissao == 1){
            painelFuncionario.setVisible(false);
        }else{
            painelAdm.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblteste = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelAdm = new javax.swing.JPanel();
        ProdutosBtn = new javax.swing.JButton();
        SairBtn = new javax.swing.JButton();
        FinancasBtn = new javax.swing.JButton();
        painelFuncionario = new javax.swing.JPanel();
        VendasBtn = new javax.swing.JButton();
        SairBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setName("FundoPrincipal"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblteste, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Loja Futuro Tech");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setText("O futuro está aqui!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, -1));

        painelAdm.setBackground(new java.awt.Color(204, 204, 204));
        painelAdm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProdutosBtn.setText("Produtos");
        ProdutosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosBtnActionPerformed(evt);
            }
        });
        painelAdm.add(ProdutosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 118, 33));

        SairBtn.setText("Sair");
        SairBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairBtnHandler(evt);
            }
        });
        painelAdm.add(SairBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 131, 33));

        FinancasBtn.setText("Finanças");
        FinancasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinancasBtnActionPerformed(evt);
            }
        });
        painelAdm.add(FinancasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 132, 33));

        getContentPane().add(painelAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 420, 50));

        painelFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        painelFuncionario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VendasBtn.setText("Vendas");
        VendasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasBtnActionPerformed(evt);
            }
        });
        painelFuncionario.add(VendasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 119, 34));

        SairBtn1.setText("Sair");
        SairBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairBtn1Handler(evt);
            }
        });
        painelFuncionario.add(SairBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 126, 34));

        getContentPane().add(painelFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja/Util/Images/Logo/Logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairBtnHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairBtnHandler
        System.exit(0);
    }//GEN-LAST:event_SairBtnHandler

    private void ProdutosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosBtnActionPerformed
       new ProdutosCadastrar().setVisible(true);
    }//GEN-LAST:event_ProdutosBtnActionPerformed

    private void VendasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasBtnActionPerformed
        new VendasView().setVisible(true);
    }//GEN-LAST:event_VendasBtnActionPerformed

    private void SairBtn1Handler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairBtn1Handler
        System.exit(0);
    }//GEN-LAST:event_SairBtn1Handler

    private void FinancasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinancasBtnActionPerformed
        new FinancasView().setVisible(true);
    }//GEN-LAST:event_FinancasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TelaInicialView(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinancasBtn;
    private javax.swing.JButton ProdutosBtn;
    private javax.swing.JButton SairBtn;
    private javax.swing.JButton SairBtn1;
    private javax.swing.JButton VendasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblteste;
    private javax.swing.JPanel painelAdm;
    private javax.swing.JPanel painelFuncionario;
    // End of variables declaration//GEN-END:variables
}
